version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/html:/var/www/html:ro
    depends_on:
      - app
    ports:
      - 8080:80
    networks:
      default:
      internal:
  app:
    build: .
    user: app
    environment:
    - PORT=8000
    - SESSIONNAME=session
    - DBSERVICE=postgres
    - DBNAME=capoost
    - DBUSER=capoost
    - DBPASSWD=JexRwZp8IbaCeT6a
    - DBHOST=db
    - DBPORT=5432
    depends_on:
    - db
    entrypoint: "bash -c 'sleep 5 && ./capoost'"
    networks:
      internal:
  db:
    image: postgres:latest
    environment:
    - POSTGRES_USER=capoost
    - POSTGRES_PASSWORD=JexRwZp8IbaCeT6a
    - POSTGRES_DB=capoost
    networks:
      internal:

networks:
  default:
  internal:
    internal: true
