version: '3.8'

services:
  nginx:
    build: ./chal
    ports:
      - "80:80"
    volumes:
      - ./chal/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./chal/html:/var/www/html:ro
    networks:
      default:
      internal:
  secretweb:
    image: nginx:latest
    volumes:
      - ./flag:/usr/share/nginx/html/flag:ro
    networks:
      internal:
networks:
  default:
    ipam:
      config:
      - subnet: 10.10.0.0/24
  internal:
    internal: true
    ipam:
      config:
      - subnet: 10.10.1.0/24
